services:
  backend:
    build:
      context: backend
    expose:
      - 8000
  proxy-dev:
    build:
      context: .
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    profiles:
      - dev
  proxy-prod:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - backend
    profiles:
      - prod
